#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="laravel-env_watcher"

prepare_service
check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting Envwatcher"
while inotifywait -q -e create,delete,modify,attrib "${NGINX_WEBROOT}"/.env; do
    print_info "Clearing Confinguration Cache due to a detected .env change"
    cd "${NGINX_WEBROOT}"
    chown -R "${NGINX_USER}":"${NGINX_GROUP}" .env
    sudo -u "${NGINX_USER}" php artisan \
                                        config:clear
    exit 0
done
