#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 30-laravel
PROCESS_NAME="laravel-env_watcher"

check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting Envwatcher"
while inotifywait -q -e create,delete,modify,attrib "${NGINX_WEBROOT}"/.env; do
    print_info "Clearing Confinguration Cache due to a detected .env change"
    cd "${NGINX_WEBROOT}"
    chown -R "${NGINX_USER}":"${NGINX_GROUP}" .env
    sudo -u "${NGINX_USER}" php artisan \
                                        config:clear
    exit 0
done
