#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="laravel-worker"

prepare_service
check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting worker"
cd "${NGINX_WEBROOT}"
sudo -u "${NGINX_USER}" php artisan \
                                            queue:work