#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 30-laravel
PROCESS_NAME="laravel-worker"

check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting worker"
cd "${NGINX_WEBROOT}"
silent sudo -u "${NGINX_USER}" php artisan \
                                            queue:work