#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="laravel-npm_run_dev"

prepare_service
check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting npm run dev"
cd "${NGINX_WEBROOT}"
sudo -u "${NGINX_USER}" npm \
                                run \
                                    dev
