#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="laravel-artisan_serve"

prepare_service
check_container_initialized
check_service_initialized init 30-laravel
liftoff

print_start "Starting Artisan Serve"
cd "${NGINX_WEBROOT}"
sudo -u "${NGINX_USER}" php \
                            artisan \
                                    serve \
                                            --no-ansi \
                                            --no-interaction \
                                            --host ${ARTISAN_SERVE_LISTEN_IP} \
                                            --port ${ARTISAN_SERVE_LISTEN_PORT} ${ARTISAN_SERVE_ARGS}
